//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Em.Workspace.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Em.Workspace.Resources.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE.
        /// </summary>
        public static string ApplicationMenu_Caption_FILE {
            get {
                return ResourceManager.GetString("ApplicationMenu_Caption_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ApplicationMenuItem_Header_Exit {
            get {
                return ResourceManager.GetString("ApplicationMenuItem_Header_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string ApplicationMenuItem_Header_Info {
            get {
                return ResourceManager.GetString("ApplicationMenuItem_Header_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ApplicationMenuItem_Header_Options {
            get {
                return ResourceManager.GetString("ApplicationMenuItem_Header_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string ApplicationMenuItem_Header_SaveAs {
            get {
                return ResourceManager.GetString("ApplicationMenuItem_Header_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Ribbon so that it is always expanded even after you click a command..
        /// </summary>
        public static string ExpandRibbon_Content {
            get {
                return ResourceManager.GetString("ExpandRibbon_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand the Ribbon (Ctrl +F1).
        /// </summary>
        public static string ExpandRibbon_Header {
            get {
                return ResourceManager.GetString("ExpandRibbon_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only the tab names on the Ribbon..
        /// </summary>
        public static string MinimizeRibbon_Content {
            get {
                return ResourceManager.GetString("MinimizeRibbon_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the Ribbon (Ctrl +F1).
        /// </summary>
        public static string MinimizeRibbon_Header {
            get {
                return ResourceManager.GetString("MinimizeRibbon_Header", resourceCulture);
            }
        }
    }
}
